version: '2.1'
services:
  dev:
    image: vadzappa/gomon-docker:1.14
    volumes:
      - ./:/app
    environment:
      - GOFLAGS=
      - GO_NO_DEBUG=true
      - GOMON_DIED_CHECK_INTERVAL=10s
    ports: 
      - 8070:8070

  users-service:
    image: vadzappa/gomon-docker:1.14
    volumes:
      - ./httpuser/:/app
    environment:
      - GOFLAGS=
      - GO_NO_DEBUG=true
      - GOMON_DIED_CHECK_INTERVAL=10s
    ports: 
      - 8090:8090
